require:
  - rubocop-rails
AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false

