services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<token from cloudflare>
  postgres:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: "postgres:14.6"
    volumes:
      - "postgres:/var/lib/postgresql/data"
  redis:
    image: "redis:7.0.8"
    volumes:
      - "redis:/data"

  web:
    build:
      context: "."
    depends_on:
      - "postgres"
      - "redis"
    env_file: .env
#    tty: true
    ports:
      - "3000:3000"

  worker:
    build:
      context: "."
    command: "worker"
    depends_on:
      - "postgres"
      - "redis"
    env_file: .env
#    tty: true

volumes:
  postgres: {}
  redis: {}