default: &default
  adapter: postgresql
  encoding: unicode
  username: "<%= ENV.fetch("POSTGRES_USER", nil) %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD", nil) %>"
  host: "<%= ENV.fetch("POSTGRES_HOST", "postgres") %>"
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", "5") %>
development:
  <<: *default
  database: "madness_development"
test:
  <<: *default
  database: "madness_test"
production:
  <<: *default
  database: "madness_production"

