# frozen_string_literal: true

tip_off = DateTime.now + 2.weeks

tournament = Tournament.field64 || Tournament.create!(tip_off:)
tournament.update!(tip_off:)

if Team.count.zero?
  [
    'Villanova',
    'Duke',
    'Baylor',
    'Florida',
    'Virginia',
    'SMU',
    'S Carolina',
    'Wisconsin',
    'Va Tech',
    'Marquette',
    'PlayIn E11',
    'UNC-Wilm',
    'ETSU',
    'New Mex St',
    'Troy',
    'PlayIn E16',
    'Gonzaga',
    'Arizona',
    'Florida St',
    'W Virginia',
    'Notre Dame',
    'Maryland',
    "St Mary's",
    'NWestern',
    'Vanderbilt',
    'VCU',
    'Xavier',
    'Princeton',
    'Bucknell',
    'FGCU',
    'N Dakota',
    'S Dak St',
    'Kansas',
    'Louisville',
    'Oregon',
    'Purdue',
    'Iowa St',
    'Creighton',
    'Michigan',
    'Miami',
    'Michigan St',
    'Oklahoma St',
    'Rhode Island',
    'Nevada',
    'Vermont',
    'Iona',
    'Jax St',
    'PlayIn MW16',
    'N Carolina',
    'Kentucky',
    'UCLA',
    'Butler',
    'Minnesota',
    'Cincinnati',
    'Dayton',
    'Arkansas',
    'Seton Hall',
    'Wichita St',
    'PlayIn S11',
    'Middle Tenn',
    'Winthrop',
    'Kent St',
    'N Kentucky',
    'Texas So'
  ].each_with_index do |team_name, i|
    Team.create!(name: team_name, starting_slot: 64 + i)
  end
end
